config/routes.rb
require 'resque/server'

NuigRnag::Application.routes.draw do
  scope ENV["RAILS_RELATIVE_URL_ROOT"] || "/" do
    root :to => "catalog#index"

    #Blacklight.add_routes(self)

    mount UserGroup::Engine => "/user_groups"

    Blacklight.add_routes(self)

    devise_for :users, :skip => [:sessions, :registrations, :passwords], class_name: 'UserGroup::User', :controllers => { :omniauth_callbacks => "user_group/omniauth_callbacks" }

    devise_scope :user do
      get '/users/sign_in', :to => 'sessions#new', :as => :new_user_session
      post '/users/sign_in', :to => 'sessions#create', :as => :user_session
      delete '/users/sign_out', :to => 'sessions#destroy', :as => :destroy_user_session
    end

    resources :objects, :only => ['new', 'edit', 'update', 'create', 'show', 'destroy'] do
      resources :files, :controller => :assets, :only => ['create','show','update','destroy']
      resources :pages
      resources :doi, :only => ['show']
    end

    resources :session, :only => ['create']

    resources :collections, :only => ['index','new','create','update','edit','destroy']
    post 'collections/:object_id/doi', to: 'doi#update', as: :collection_doi
    post 'collections/:id/organisations', to: 'institutes#set', as: :collection_organisations
    post 'collections/:id/batch', to: 'batch_ingest#create', as: :batch_ingest
  
    put 'collections/:id/licences', to: 'collections#set_licence', as: :collection_licence
    put 'objects/:id/licences', to: 'objects#set_licence', as: :object_licence

    get 'objects/:id/access', to: 'access_controls#edit', as: :access_controls
    put 'objects/:id/access', to: 'access_controls#update'
  
    resources :organisations, controller: :institutes, :only => ['index','show', 'new', 'create', 'destroy', 'edit', 'update']

    match 'association' => 'institutes#associate', :via => :post, :as => :new_association
    match 'association' => 'institutes#disassociate', :via => :delete, :as => :disassociation
    match 'manage_users' => 'manage_users#new', :via => :get, :as => :manage_users
    match 'manage_users' => 'manage_users#create', :via => :post, :as => :new_manage_user

    resources :licences

    match 'session/:id' => 'session#create', :via => :get, :as => :lang

    match 'error/404' => 'error#404', :via => :get
    match 'error/422' => 'error#422', :via => :get
    match 'error/500' => 'error#500', :via => :get

    get '/404' => 'error#error_404'
    get '/422' => 'error#error_422'
    get '/500' => 'error#error_500'

    match 'objects/:id/metadata' => 'metadata#show', :via => :get, :as => :object_metadata, :defaults => { :format => 'xml' }
    match 'objects/:id/metadata' => 'metadata#update', :via => :put
    match 'objects/:id/citation' => 'objects#citation', :via => :get, :as => :citation_object
    match 'objects/:id/history' => 'object_history#show', :via => :get, :as => :object_history
    match 'objects/:id/datastreams/:stream' => 'datastream_version#show', :via => :get, :as => :datastream_version
    match 'objects/:object_id/files/:id/download' => 'assets#download', :via => :get, :as => :file_download

    match 'objects/:id/status' => 'objects#status', :via => :put, :as => :status_update
    match 'objects/:id/status' => 'objects#status', :via => :get, :as => :status

    match 'maps/:id' => 'maps#show', :via => :get, :as => :maps
    #match 'timeline_json' => 'timeline#get', :via => :get

    match 'collections/:id/publish' => 'collections#publish', :via => :put, :as => :publish
    # Added review method to collections controller
    match 'collections/:id/review' => 'collections#review', :via => :put, :as => :review
    
    match 'collections/:id/cover' => 'collections#add_cover_image', :via => :put, :as => :add_cover_image

    match '/privacy' => 'static_pages#privacy', :via => :get
    match '/workspace' => 'workspace#index', :via => :get
    match '/admin_tasks' => 'static_pages#admin_tasks', :via => :get

    match 'surrogates/:id' => 'surrogates#update', :via => :put, :as => :surrogates_generate
    match 'surrogates/:id' => 'surrogates#show', :via => :get, :as => :surrogates
    match 'surrogates/:id/download' => 'surrogates#download', :via => :get, :as => :surrogate_download

    match 'collections/:id' => 'catalog#show', :via => :get

    #API paths
    match 'get_objects' => 'objects#index', :via => :post
    match 'related' => 'objects#related', :via => :get
    match 'get_assets' => 'assets#list_assets', :via => :post, :as => :list_assets

    # need to put in the 'system administrator' role here
    authenticate do
      mount Resque::Server, :at => "/resque"
    end
  end

  match 'pages/*id' => 'high_voltage/pages#show', :via => :get
end

app/views/shared/_access_controls_form.html.erb
<div class="dri_ingest_form_container">
	<div class="dri_ingest_form" style="width: 100%">

        <%= form_for @object, as: :batch, :url => {:controller=>"access_controls", :action=>"update"}, :method=>"put", :html => {:class => 'form-vertical'} do |f| %>

        <%= render :partial => "shared/access_controls", :locals => {:f => f,:record => @object } %>
        <%= f.submit t('dri.views.objects.buttons.save'), :class => "dri_button_green dri_w330", :id => "save_access_controls" %>
            
    <% end %>
  </div>
</div>

app/views/shared/_add_institute.html.erb
<script>
function fileUploadHelper(thisObj) {
    $("#institution_logo").html(($(thisObj).val()).replace("C:\\fakepath\\", ""));
}
</script>

<div class="dri_institutes_title" id="accordion">

    <div class="dri_add_institute_link">
              <a title="<%= t('dri.views.collection.institute.add') %>" id="new_institute" data-toggle="collapse" data-parent="#accordion" href="#dri_add_institutes_block" ><i class="fa fa-plus">&nbsp;</i><%= t('dri.views.collection.institute.add') %></a></p>

    </div>
    <div id="dri_add_institutes_block" class="collapse">
    <div class="dri_file_upload">
                <%= form_for(@inst, remote: true) do |f| %>
                    <div>
                        <a class='btn btn-default' href='javascript:;'>
                        <h5 class="dri_upload_file_text"><i class="fa fa-upload">&nbsp;</i><%= "#{t('dri.views.collection.institute.form.logo')}"%></h5>
                        <p>(recommended height 75px)</p>
                        <%= f.file_field :logo, :required=>'required', :accept=>'image/png,image/jpeg', :onchange=>'fileUploadHelper($(this));' %>
                        <h5 id="institution_logo">No File</h5>
                        </a>
                    </div>
                    <%= hidden_field_tag 'object', @object.id %>
                    <label> <%= t('dri.views.collection.institute.form.name') %></label>
                    <%= f.text_field :name, :required=>'required' %>
                    <label><%= t('dri.views.collection.institute.form.url') %></label>
                    <%= f.url_field :url, :required=>'required'  %>

                

                    <%= f.submit t('dri.views.collection.institute.add'), :id => 'add_institute', :class=>'btn dri_grey_button' %>
                <% end %>
    </div>


</div>
</div>
<!--  -->

app/views/shared/_cookies.html.erb
<div class="alert alert-block">
  <a class="close" href="#" name="accept_cookies" id="accept_cookies" data-dismiss="alert" onclick="$.cookie('accept_cookies', 'yes', { path: '/', expires: 10000 });"><%= t('dri.application.cookies.accept') %></a>
  <h4 class="alert-heading"><%= t('dri.application.cookies.header') %></h4>
  <%= it 'dri.application.cookies.message', privacy_statement: It.link('http://www.dri.ie/privacy-statement'), cookies_help: It.link("#") %>
</div>

app/views/shared/_deposit_terms.en.html.erb
<div>
<h4 id="deposit_agreement_title"><%= t('dri.application.terms.deposit_header') %></h4>

<h5>Definitions</h5>

<p><strong>Access permissions</strong>  The restrictions placed on access by the Depositor.</p>

<p><strong>Authorise/ De-authorise</strong>  Authorisation is a function which specifies access rights to resources. Authorisation is related to computer security. A user with authorisation is a user with official power or permission to perform certain tasks. This may include permission to upload or modify digital objects and metadata in the system.</p>

<p><strong>Bulk Export</strong>  Any act of copying a digital object and its associated metadata from the System.</p>

<p><strong>Deposit</strong>  Any act of uploading or modifying, and publishing file or digital object and its associated metadata to the System.</p>

<p><strong>Depositor</strong>  The person or persons authorised by the Organisational Manager to upload or modify digital objects to the system.</p>

<p><strong>Digital Object</strong>  A digital object refers to any material and its associated metadata provided by the Depositor under the title applied in the metadata and deposited under the terms and conditions of the Organisational Manager Agreement and the Deposit Terms and Conditions.</p>

<p><strong>Digital Object Identifier</strong>  The International DOI Foundation has developed DOI names (Digital Object Identifier names) as actionable persistent identifiers for content­related entities. The system then provides for persistent and actionable identification and interoperable exchange of managed information on digital networks.</p>

<p><strong>Persistent identifier</strong>  Persistent identifiers are unique, maintainable links to digital objects which provide continuous access to the
object, even if it moves servers or moves to the responsibility of a different organisation.</p>

<p><strong>Organisational Manager</strong>  The person or persons who has authority, on behalf of their Organisation, to deposit material in the Repository and to undertake all other actions outlined in the Organisational Manager Agreement (including the application of licences and access permissions to digital objects and the assignment of roles to additional users who have permission to deposit).</p>

<p><strong>Roles</strong>  The set of tasks an individual has permissions to carry out in the Repository, as granted by the Organisational Manager.</p>

<p><strong>System</strong>  The Digital Repository of Ireland technical repository infrastructure.</p>

<p><strong>The Repository</strong>  The Digital Repository of Ireland </p>

<p><strong>Users</strong>  Individuals registered by the Repository to use the Digital Objects or a member of an institution registered by the University to use the Repository under this Organisational Agreement. </p>

<p>This non exclusive, irrevocable and perpetual license ensures that the original creators of the digital object retain the ownership, copyright and associated intellectual property rights in all deposited digital material.</p>

<p>The Depositor warrants that they are the owner of the copyright, and any associated intellectual property rights, of the digital objects; or they are duly authorised by the owner, or owners, of these rights and capable of granting under this agreement a licence under the terms outlined below</p>

<h5><strong>The Depositor:</strong> </h5>

<p>D1. Has authority, on behalf of their Organisation, to deposit material in the Repository and to undertake all other actions outlined below (including the application of licences and access permissions to digital objects and the assignment of roles to additional users who have permission to deposit). </p>

<p>D2. Will ensure that correct rights statements, and where applicable, licensing statements, are applied to the digital objects in the System. </p>

<p>D3. Will ensure that, in the case of an Orphan Work, a diligent search is carried out in good faith in respect of each Work, prior to the use of the Work, by consulting the appropriate sources for the Work in question. </p>

<p>Will prepare a record of each diligent search in respect of an Orphan Work, and provide this record to the Repository. </p>

<p>Will ensure that, in the case of an Orphan Work, its status as an Orphan Work is noted in the metadata associated with the Work. </p>

<p>D4. Will ensure that in the case of research data with human subjects that consents collected are ethically and legally appropriate and sufficient to allow deposit to DRI. </p>

<p>Will promptly notify The Repository of any copyright, confidentiality, privacy, data protection, defamation, or similar or related issues pertaining to the digital objects. </p>

<p>Will act promptly to edit access permission where any such issue has arisen. </p>

<p>Will act promptly in association with the Repository to ensure that the most appropriate action is taken, including but not limited to actions pursuant to any applicable notice and action procedure. </p>


<p>D5. Will ensure that appropriate access permissions are applied to the digital objects in the System. </p>

<p>The Repository will not assume responsibility for the setting of access permissions or access given in error by the depositor. All access to restricted content is managed by the depositing institution who can grant and revoke access to collections and digital objects. </p>

<p>D6. Will ensure that the correct organisational affiliation and any associated logos are applied to each digital object in the System as appropriate. </p>

<p>D7. Will ensure that each digital object in the system has an associated metadata record. </p>

<p>D8. Will ensure that the digital objects deposited meet the Repository documented standards (including but not limited to those pertaining to licensing, metadata and formats). </p>

<p>D9. Grants the Repository the right to make available the digital object according to the access permissions set by the depositor. </p>

<p>D10. Will ensure that contact details for the organisation are applied to collection level metadata, on a per collection basis and updated as necessary. </p>

<p>D11. Grants to the repository the right to assign its benefits, rights and obligations under this Agreement to any third party. </p>

<p>D12. Understands that, ultimately, it is solely a matter for the Repository whether or not an object will be stored or retained in or removed from the system, or made available to the public, including but not limited to actions persuant to any notice and action procedure. </p>


<h5><strong>The Repository:</strong> </h5>

<p>R1. Does not assume sole responsibility for access to and availability of any digital object. Depositors are allowed to make their own digital objects available in any means that they wish. </p>

<p>R2. Will take all reasonable and lawful steps to ensure that the permissions granted by the depositor will be enforced by the system. </p>

<p>R3. Will display the rights statements applied to digital object by the Depositor in the System. R4. Has the right to aggregate metadata associated with the digital objects. </p>

<p>R5. Will assign a persistent identifier to each digital object. </p>

<p>R6. Will ensure that all metadata in the Repository is publicly accessible. </p>

<p>R7. Will make available statistics to the Organisational Manager on the use of the digital objects. </p>

<p>R8. Will decide whether or not an object will be stored or retained in or removed from the system, or made available to the public, including but not limited to actions persuant to any notice and action procedure. </p>

</div>

app/views/shared/_display_licence.html.erb
<dt class="dri_licence"><%= t('dri.views.fields.licence') %></dd>
<dd class="dri_licence"><% if @document.licence.present? %>
      <% if @document.licence.is_a? Array %>
        <%= "#{@document.licence.first}" %>
      <% else %>
        <% if @document.licence.name == "All Rights Reserved" %>
          <% @document.licence.name = t('dri.views.licences.all_rights_reserved') %>
        <% end %>
        <% if @document.licence.url.present? %>
          <%= link_to "#{@document.licence.name}", @document.licence.url, :target => "_blank" %>
        <% else %>
          <%= "#{@document.licence.name}" %>
        <% end %>
      <% end %>
      <%# these logos are too ugly - text looks better %>
      <%# image_tag(@licence.logo) unless @licence.logo.blank? %>
  <% end %>
</dd>

app/views/shared/_form_licence.html.erb
<fieldset id="licence">
	<span><%= f.label "#{t('dri.views.fields.licence')}"%><i class="dri_help_popover fa fa-info-circle fa-1" data-content="<%= t('dri.help.fields.licence_text') %>" data-original-title="<%= t('dri.help.fields.licence')%>" data-trigger="hover" data-placement="right"></i></span>
	<select class="dri_licence_select" name="batch[licence]" id="batch_licence">
    <% @licences.each do |text, value| %>
      <% if @document[:licence_tesim].present? &&  @document[:licence_tesim].first == value %>
        <option selected="selected" value="<%= value %>" label="<%= value %>" title="<%= text %>"><%= text %></option>
      <% else %>
        <option value="<%= value %>" label="<%= value %>" title="<%= text %>"><%= text %></option>
      <% end %>
    <% end %>
</fieldset>

<%= f.submit t('dri.views.catalog.buttons.submit'), :class => "dri_button_green dri_w230", :id => "set_licence" %>

app/views/shared/_header_browse_sort_by.html.erb
<% if has_browse_params? %>
    <!-- navigation to allow the user to determine how the search result are sorted e.g. by relevance, A to Z, Z to A -->
    <nav id="dri_sort_nav_id" class="dri_sort_nav" >
      <select id="dri_sort_options_id" class="dri_sort_options" name="sort_options" data-content="<%= t('dri.help.dri_sort_options') %>"  data-original-title="<%= t('dri.help.dri_sort_options_title')%>" data-trigger="hover" data-placement="right">
        <%- blacklight_config.sort_fields.each do |sort_key, field| %>
            <% if field.label == current_sort_field.label %>
                <option value="<%= url_for(params_for_search.merge(:sort => sort_key)) %>" selected><%= (field.label).capitalize %></option>
            <% else %>
                <option value="<%= url_for(params_for_search.merge(:sort => sort_key)) %>"><%= (field.label).capitalize %></option>
            <% end %>
        <%- end -%>
      </select>
    </nav>

<% end %>

app/views/shared/_header_crumbtrail.html.erb
<!-- start dri_crumbtrail_nav_container -->
<% if @document %>
    <div id="dri_crumbtrail_nav_container_id">
      <ol class="breadcrumb">
      <% unless @document.is_a?(DRI::Batch) %>
          <% if @document[Solrizer.solr_name('ancestor_id', :stored_searchable, type: :string).to_sym].present? %>
            <% @document[Solrizer.solr_name('ancestor_id', :stored_searchable, type: :string).to_sym].to_enum.with_index.reverse_each do |ancestor_id, index| %>
              <li><%= link_to @document[Solrizer.solr_name('ancestor_title', :stored_searchable, type: :string).to_sym][index], main_app.catalog_path(ancestor_id) %></li>
            <% end %>
          <% end %>
          <% if @generic_file %>
            <li><%= link_to truncate(@document[Solrizer.solr_name('title', :stored_searchable, type: :string).to_sym].first, length:50), main_app.catalog_path(@document.id) %></li>
            <li class="active"><%= @generic_file.label %></li>
          <% else %>
            <li class="active"><%= truncate(@document[Solrizer.solr_name('title', :stored_searchable, type: :string).to_sym].first, length:50) %></li>
          <% end %>
      <% end %>
      </ol>
    </div>
<% end %>

<% if @collection %>
    <div id="dri_crumbtrail_nav_container_id">
      <ol class="breadcrumb">
              <li class="active"><%= link_to( t('dri.views.objects.legends.view_collection'), catalog_path(@collection), :id => 'view_collection' ) %></li>
      </ol>
    </div>
<% end %>
<!-- close dri_crumbtrail_nav_container -->

app/views/shared/_header_lang.html.erb
<% lang_params = {:path => request.fullpath} %>

<% if I18n.locale == :en %>
<% lang_params[:id] = 'ga' %>
<ul class="dropdown">
	<li>
		<%= link_to 'English', '#', :"data-toggle" => "dropdown", id: :en %>
		 <i class="icon-caret-down"></i>
		<ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
			<%= link_to lang_path(lang_params), id: :ga do %>
			<li>
				Gaeilge
			</li>
			<% end %>
		</ul>
	</li>
</ul>
<% else %>
<% lang_params[:id] = 'en' %>
<ul class="dropdown">
	<%= link_to 'Gaeilge', '#', :"data-toggle" => "dropdown", id: :ga %>
	<i class="icon-caret-down"></i>
	<ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
		<%= link_to lang_path(lang_params), id: :en  do %>
		<li>
			English
		</li>
		<% end %>
	</ul>
</ul>
<% end %>

app/views/shared/_header_main_workspace_dropdown.html.erb
<% if (request.path.include? "/bookmarks") || (request.path.include? "/user_groups/users") || (request.path.include? "/search_history") || (request.path.include? "/saved_searches") %>
<li class="dropdown active dri_dropdown">
	<% else %>
<li class="dropdown dri_dropdown">
	<% end %>
	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= t('dri.headerlinks.workspace') %> <span class="caret"></span></a>
	<ul class="dropdown-menu" role="menu">
		<% if request.path.include? "/user_groups/users" %>
		<li role="presentation" class="active">
			<% else %>
		<li role="presentation">
			<% end %>
			     
            <%= link_to user_group.user_path(current_user) do %>
            <i class="fa fa-user"></i>&nbsp;<%= current_user[:first_name].to_s %>
            <% end %>

		</li>
		<% if request.path.include? "/bookmarks" %>
		<li role="presentation" class="active">
			<% else %>
		<li role="presentation">
			<% end %>
			<%= link_to t('blacklight.header_links.bookmarks'), bookmarks_path({:mode => 'collections', :view => 'grid'}), :tabindex => "-1" %>
		</li>
		<% if request.path.include? "/saved_searches" %>
		<li role="presentation" class="active">
			<% else %>
		<li role="presentation">
			<% end %>
			<%= link_to t('blacklight.header_links.saved_searches'), saved_searches_path, :tabindex => "-1", :id => 'saved_search' %>
		</li>
	</ul>
</li>

app/views/shared/_header_navbar.html.erb
<!-- Header to be displayed to users -->
<header id="dri_header_container_id" class="dri_header_container hidden-xs">
<%= render 'shared/header_navbar_logo' %>

	<%= render 'shared/header_navbar_social_media' %>
	<div class="dri_authentication_search_container">
	           <%= render 'shared/header_navbar_user' %>
	    <%= render 'catalog/dri_search_form' %>


	</div>

</header><!-- close dri_header_container -->

<%= render 'shared/header_main_nav' %>
<% if !is_root? %>
<%= render 'shared/header_crumbtrail' %>

<%= render 'shared/header_browse_features' %>
<% end %>

app/views/shared/_header_navbar_logo.html.erb
<%= link_to main_app.root_path do %>
    <div id="dri_ident_id" class="dri_ident"></div>
<% end %>

app/views/shared/_header_navbar_social_media.html.erb
<div id="dri_social_media_container_id"
class="dri_social_media_container">

	<nav id="dri_social_media_nav_id" class="dri_social_media_nav" >
		<ul id="dri_social_media_links_id" class="dri_social_media_links" data-content="<%= t('dri.help.social_media_links') %>"  data-original-title="<%= t('dri.help.social_media_links_title')%>" data-trigger="hover" data-placement="right">
			<%= link_to "https://twitter.com/library_MU", :id => "follow_twitter", :target => "_blank" do %>
			<li> 
				<i class="fa fa-twitter fa-lg"></i>
			</li>
			<% end %>
			<%= link_to "https://www.facebook.com/Maynooth-University-Library-115927011780537/", :id => "follow_facebook", :target => "_blank" do %>
			<li>
				<i class="fa fa-facebook-official fa-lg"></i>
			</li>
			<% end %>
			<%= link_to "https://vimeo.com/CHANGEME", :id => "follow_vimeo", :target => "_blank" do %>
                        <li>
                                 <i class="dri_no_display"></i>
                         </li>
                         <% end %>
                      <%= link_to "http://www.slideshare.net/CHANGEME", :id => "http://www.slideshare.net/dri_ireland", :target => "_blank" do %>
                         <li>
                                 <i class="dri_no_display"></i>
                         </li>
			<%end%>
		</ul>
	</nav>
</div>
<!-- search term input block (including any required hidden fields) to allow user to input a search term(s)  -->