config/routes.rb
require 'resque/server'

NuigRnag::Application.routes.draw do
  scope ENV["RAILS_RELATIVE_URL_ROOT"] || "/" do
    root :to => "catalog#index"

    #Blacklight.add_routes(self)

    mount UserGroup::Engine => "/user_groups"

    Blacklight.add_routes(self)

    devise_for :users, :skip => [:sessions, :registrations, :passwords], class_name: 'UserGroup::User', :controllers => { :omniauth_callbacks => "user_group/omniauth_callbacks" }

    devise_scope :user do
      get '/users/sign_in', :to => 'sessions#new', :as => :new_user_session
      post '/users/sign_in', :to => 'sessions#create', :as => :user_session
      delete '/users/sign_out', :to => 'sessions#destroy', :as => :destroy_user_session
    end

    resources :objects, :only => ['new', 'edit', 'update', 'create', 'show', 'destroy'] do
      resources :files, :controller => :assets, :only => ['create','show','update','destroy']
      resources :pages
      resources :doi, :only => ['show']
    end

    resources :session, :only => ['create']

    resources :collections, :only => ['index','new','create','update','edit','destroy']
    post 'collections/:object_id/doi', to: 'doi#update', as: :collection_doi
    post 'collections/:id/organisations', to: 'institutes#set', as: :collection_organisations
    post 'collections/:id/batch', to: 'batch_ingest#create', as: :batch_ingest
  
    put 'collections/:id/licences', to: 'collections#set_licence', as: :collection_licence
    put 'objects/:id/licences', to: 'objects#set_licence', as: :object_licence

    get 'objects/:id/access', to: 'access_controls#edit', as: :access_controls
    put 'objects/:id/access', to: 'access_controls#update'
  
    resources :organisations, controller: :institutes, :only => ['index','show', 'new', 'create', 'destroy', 'edit', 'update']

    match 'association' => 'institutes#associate', :via => :post, :as => :new_association
    match 'association' => 'institutes#disassociate', :via => :delete, :as => :disassociation
    match 'manage_users' => 'manage_users#new', :via => :get, :as => :manage_users
    match 'manage_users' => 'manage_users#create', :via => :post, :as => :new_manage_user

    resources :licences

    match 'session/:id' => 'session#create', :via => :get, :as => :lang

    match 'error/404' => 'error#404', :via => :get
    match 'error/422' => 'error#422', :via => :get
    match 'error/500' => 'error#500', :via => :get

    get '/404' => 'error#error_404'
    get '/422' => 'error#error_422'
    get '/500' => 'error#error_500'

    match 'objects/:id/metadata' => 'metadata#show', :via => :get, :as => :object_metadata, :defaults => { :format => 'xml' }
    match 'objects/:id/metadata' => 'metadata#update', :via => :put
    match 'objects/:id/citation' => 'objects#citation', :via => :get, :as => :citation_object
    match 'objects/:id/history' => 'object_history#show', :via => :get, :as => :object_history
    match 'objects/:id/datastreams/:stream' => 'datastream_version#show', :via => :get, :as => :datastream_version
    match 'objects/:object_id/files/:id/download' => 'assets#download', :via => :get, :as => :file_download

    match 'objects/:id/status' => 'objects#status', :via => :put, :as => :status_update
    match 'objects/:id/status' => 'objects#status', :via => :get, :as => :status

    match 'maps/:id' => 'maps#show', :via => :get, :as => :maps
    #match 'timeline_json' => 'timeline#get', :via => :get

    match 'collections/:id/publish' => 'collections#publish', :via => :put, :as => :publish
    # Added review method to collections controller
    match 'collections/:id/review' => 'collections#review', :via => :put, :as => :review
    
    match 'collections/:id/cover' => 'collections#add_cover_image', :via => :put, :as => :add_cover_image

    match '/privacy' => 'static_pages#privacy', :via => :get
    match '/workspace' => 'workspace#index', :via => :get
    match '/admin_tasks' => 'static_pages#admin_tasks', :via => :get

    match 'surrogates/:id' => 'surrogates#update', :via => :put, :as => :surrogates_generate
    match 'surrogates/:id' => 'surrogates#show', :via => :get, :as => :surrogates
    match 'surrogates/:id/download' => 'surrogates#download', :via => :get, :as => :surrogate_download

    match 'collections/:id' => 'catalog#show', :via => :get

    #API paths
    match 'get_objects' => 'objects#index', :via => :post
    match 'related' => 'objects#related', :via => :get
    match 'get_assets' => 'assets#list_assets', :via => :post, :as => :list_assets

    # need to put in the 'system administrator' role here
    authenticate do
      mount Resque::Server, :at => "/resque"
    end
  end

  match 'pages/*id' => 'high_voltage/pages#show', :via => :get
end

app/controllers/catalog_controller.rb
# -*- encoding : utf-8 -*-
require 'institute_helpers'
require 'iso8601'
require 'iso-639'

# Blacklight catalog controller
#
class CatalogController < ApplicationController
  include Blacklight::Catalog
  include Hydra::Controller::ControllerBehavior
  # Extend Blacklight::Catalog with Hydra behaviors (primarily editing).
  include Hydra::AccessControlsEnforcement

  include TimelineHelper

  #This method shows the DO if the metadata is open
  #Rather than before where the user had to have read permissions on the object all the time
  def enforce_search_for_show_permissions
    enforce_permissions!("show_digital_object",params[:id])
  end
  # These before_filters apply the hydra access controls
  before_filter :enforce_search_for_show_permissions, :only=>:show

  # Workaround to user_parameters not being persisted in search_params_filter
  before_filter :modify_user_parameters, :only=>:index

  # This applies appropriate access controls to all solr queries
  CatalogController.solr_search_params_logic += [:add_access_controls_to_solr_params]
  # This filters out objects that you want to exclude from search results, like FileAssets
  CatalogController.solr_search_params_logic += [:search_date_dange, :subject_temporal_filter, :subject_place_filter, :exclude_unwanted_models]
  #CatalogController.solr_search_params_logic += [:exclude_unwanted_models, :exclude_collection_models]

  configure_blacklight do |config|
    config.per_page = [9,18,36]
    config.default_per_page = 9
    config.metadata_lang = ['all','gle','enl']
    config.default_metadata_lang = 'all'

    config.default_solr_params = {
      :defType => "edismax",
      :qt => 'search',
      :rows => 9
    }
    config.show.partials << :show_maplet

    # solr field configuration for search results/index views
    config.index.title_field = solr_name('title', :stored_searchable, type: :string)
    config.index.record_tsim_type = solr_name('has_model', :stored_searchable, type: :symbol)

    # solr field configuration for document/show views
    config.show.title_field = solr_name('title', :stored_searchable, type: :string)
    config.show.display_type_field = solr_name('file_type', :stored_searchable, type: :string)

    config.show.document_actions.delete(:email)
    config.show.document_actions.delete(:sms)
    config.show.document_actions.delete(:citation)

    # solr fields that will be treated as facets by the blacklight application
    #   The ordering of the field names is the order of the display
    #
    # Setting a limit will trigger Blacklight's 'more' facet values link.
    # * If left unset, then all facet values returned by solr will be displayed.
    # * If set to an integer, then "f.somefield.facet.limit" will be added to
    # solr request, with actual solr request being +1 your configured limit --
    # you configure the number of items you actually want _displayed_ in a page.
    # * If set to 'true', then no additional parameters will be sent to solr,
    # but any 'sniffed' request limit parameters will be used for paging, with
    # paging at requested limit -1. Can sniff from facet.limit or
    # f.specific_field.facet.limit solr request params. This 'true' config
    # can be used if you set limits in :default_solr_params, or as defaults
    # on the solr side in the request handler itself. Request handler defaults
    # sniffing requires solr requests to be made with "echoParams=all", for
    # app code to actually have it echo'd back to see it.
    #
    # :show may be set to false if you don't want the facet to be drawn in the
    # facet bar

    #config.add_facet_field solr_name('status', :facetable), :label => 'Record Status'
    #config.add_facet_field "private_metadata_isi", :label => 'Metadata Search Access', :helper_method => :label_permission
    #config.add_facet_field "master_file_isi", :label => 'Master File Access',  :helper_method => :label_permission
    #}
    # Configure facets for dateRange although NOT displayed
    #config.add_facet_field "cdateRange", :show => false
    #config.add_facet_field "pdateRange", :label => 'Published Date', :show => false
    #config.add_facet_field "sdateRange", :label => 'Subject (temporal)', :show => false

    config.add_facet_field "sdateRange", :label => 'Subject (Temporal)', :partial => 'custom_date_range'

    config.add_facet_field solr_name('subject', :facetable), :limit => 20
    #config.add_facet_field solr_name('subject_gle', :facetable), :label => 'Subjects (in Irish)'
    #config.add_facet_field solr_name('subject_eng', :facetable), :label => 'Subjects (in English)'
    config.add_facet_field solr_name('geographical_coverage', :facetable), :helper_method => :parse_location, :limit => 20
    config.add_facet_field solr_name('placename_field', :facetable), :label => 'Placename', :show => false
    config.add_facet_field solr_name('geojson', :symbol), :limit => -2, :label => 'Coordinates', :show => false
    #config.add_facet_field solr_name('geographical_coverage_gle', :facetable), :label => 'Subject (Place) (in Irish)', :limit => 20
    #config.add_facet_field solr_name('geographical_coverage_eng', :facetable), :label => 'Subject (Place) (in English)', :limit => 20
    config.add_facet_field solr_name('temporal_coverage', :facetable), :helper_method => :parse_era, :limit => 20, :show => false
    #config.add_facet_field solr_name('temporal_coverage_gle', :facetable), :label => 'Subject (Era) (in Irish)', :limit => 20
    #config.add_facet_field solr_name('temporal_coverage_eng', :facetable), :label => 'Subject (Era) (in English)', :limit => 20
    #config.add_facet_field solr_name('name_coverage', :facetable), :label => 'Subject (Name)', :limit => 20
    #config.add_facet_field solr_name('creator', :facetable), :label => 'creators', :show => false
    #config.add_facet_field solr_name('contributor', :facetable), :label => 'contributors', :show => false
    config.add_facet_field solr_name('person', :facetable), :limit => 20
    config.add_facet_field solr_name('language', :facetable), :helper_method => :label_language, :limit => true
    #config.add_facet_field solr_name('creation_date', :dateable), :label => 'Creation Date', :date => true
    #config.add_facet_field solr_name('published_date', :dateable), :label => 'Published/Broadcast Date', :date => true
    #config.add_facet_field solr_name('width', :facetable, type: :integer), :label => 'Image Width'
    #config.add_facet_field solr_name('height', :facetable, type: :integer), :label => 'Image Height'
    #config.add_facet_field solr_name('area', :facetable, type: :integer), :label => 'Image Size'

    # duration is measured in milliseconds
    #config.add_facet_field solr_name('duration_total', :stored_sortable, type: :integer), :label => 'Total Duration'

    #config.add_facet_field solr_name('channels', :facetable, type: :integer), :label => 'Audio Channels'
    #config.add_facet_field solr_name('sample_rate', :facetable, type: :integer), :label => 'Sample Rate'
    #config.add_facet_field solr_name('bit_depth', :facetable, type: :integer), :label => 'Bit Depth'
    #config.add_facet_field solr_name('file_count', :stored_sortable, type: :integer), :label => 'Number of Files'
    #config.add_facet_field solr_name('file_size_total', :stored_sortable, type: :integer), :label => 'Total File Size'
    #config.add_facet_field solr_name('mime_type', :facetable), :label => 'MIME Type'
    #config.add_facet_field solr_name('file_format', :facetable), :label => 'File Format'
    config.add_facet_field solr_name('file_type_display', :facetable)
    #config.add_facet_field solr_name('object_type', :facetable), :label => 'Type (from Metadata)'
    #config.add_facet_field solr_name('depositor', :facetable), :label => 'Depositor'
    config.add_facet_field solr_name('institute', :facetable), :limit => 10 
    config.add_facet_field solr_name('root_collection_id', :facetable), :helper_method => :collection_title, :limit => 10 

    # TODO Temporarily added to test sub-collection belonging objects filter in object results view
    config.add_facet_field solr_name('ancestor_id', :facetable), :label => 'ancestor_id', :helper_method => :collection_title, :show => false

    config.add_facet_field solr_name('is_collection', :facetable), :label => 'is_collection', :helper_method => :is_collection, :show => false

    # Have BL send all facet field names to Solr, which has been the default
    # previously. Simply remove these lines if you'd rather use Solr request
    # handler defaults, or have no facets.
    config.add_facet_fields_to_solr_request!

    # solr fields to be displayed in the index (search results) view
    #   The ordering of the field names is the order of the display
    config.add_index_field solr_name('title', :stored_searchable, type: :string), :label => 'title'
    config.add_index_field solr_name('subject', :stored_searchable, type: :string), :label => 'subjects'
    config.add_index_field solr_name('creator', :stored_searchable, type: :string), :label => 'creators'
    config.add_index_field solr_name('format', :stored_searchable), :label => 'format'
    config.add_index_field solr_name('file_type_display', :stored_searchable, type: :string), :label => 'Mediatype'
    config.add_index_field solr_name('language', :stored_searchable, type: :string), :label => 'language', :helper_method => :label_language
    config.add_index_field solr_name('published', :stored_searchable, type: :string), :label => 'Published:'
    

    # solr fields to be displayed in the show (single result) view
    #   The ordering of the field names is the order of the display
    config.add_show_field solr_name('title', :stored_searchable, type: :string), :label => 'title'
    config.add_show_field solr_name('subtitle', :stored_searchable, type: :string), :label => 'subtitle:'
    config.add_show_field solr_name('description', :stored_searchable, type: :string), :label => 'description', :helper_method => :render_description

app/views/catalog/_browse_view_list_collection.html.erb
<article class="dri_result_object dri_clearfix" id="<%= document.id.to_s %>">
  <div class="dri_content_list_collection">
           <% if params[:controller] == 'bookmarks' && params[:action] == 'index' %>

                <%= link_to bookmark_path(document.id), method: :delete, :id => 'remove_bookmark' do %>
                <span class="dri_remove_bookmark"><i class="fa fa-bookmark"></i></span>
                <% end %>
            <% end %>

    <!-- close image -->

    <div class="dri_content_list_collection_data">
      <%= link_to(url_for_document(document), document_link_params(document, {:counter => document_counter_with_offset(document_counter)} )) do %>
          <h4><%= document[Solrizer.solr_name('title', :stored_searchable, type: :string).to_sym][0] %></h4>
      <% end %>
      <p>
        <%= truncate_description(document[Solrizer.solr_name('description', :stored_searchable, type: :string).to_sym][0], 280).html_safe %>
      </p>
      <p class="dri_publishing_institute">
	    <% get_depositing_institute ( document ) %>
		<% if @depositing_institute.present? %>
		    <%= @depositing_institute.name %>
		<% else %>
			N/A
		<% end %>
      </p>
      <%# If ROOT COLLECTION %>
      <% if document[Solrizer.solr_name('collection_id', :stored_searchable, type: :string)].nil? %>
          <% collection_objects_params = { :f => {Solrizer.solr_name('root_collection_id', :facetable).to_sym => [document[Solrizer.solr_name('root_collection_id', :stored_searchable, type: :string)].first]}, :mode => "objects", :search_field => "all_fields", :view => params[:view] } %>
      <% else %>
          <%# If SUB-COLLECTION %>
          <% collection_objects_params = { :f => {Solrizer.solr_name('ancestor_id', :facetable).to_sym => [document.id]}, :mode => "objects", :search_field => "all_fields", :view => params[:view] } %>
      <% end %>
      <%= link_to (catalog_index_path(collection_objects_params)) do %>
          <div class="dri_num_list_objects">
            <span class="dri_object_text_num">
              <%= t('dri.views.catalog.forms.objects_in_collection') + " (" + count_items_in_collection(document[:id]).to_s + ")" %>
            </span>
          </div>
      <% end %> <!-- close dri_num_objects -->
    </div>
  </div>
  <%= link_to(url_for_document(document), document_link_params(document, {:counter => document_counter_with_offset(document_counter)} )) do %>
      <div class="dri_image">
        <% image = cover_image ( document ) %>
        <% unless image.nil? %>
            <%= image_tag image, :width=>"200" %>
        <% else %>
            <%= image_tag "no_image.png", :width=>"200" %>
        <% end %>
      </div>
  <% end %>

  <% if params[:controller] == 'bookmarks' && params[:action] == 'index' %>
      <%= link_to 'remove bookmark', bookmark_path(document.id), method: :delete, :id => 'remove_bookmark' %>
  <% end %>
  <!-- close content_block -->
</article>

app/views/catalog/_constraints_element.html.erb
<%- # local params:
    # label 
    # value
    # options =>
    #   :remove => url for a remove constraint link
    #   :classes => array of classes to add to container span
    options ||= {}
    options[:escape_label] = true unless options.has_key?(:escape_label)
    options[:escape_value] = true unless options.has_key?(:escape_value)
-%>
  
            	<li><span class="search_mini_icon"></span><%= options[:escape_value] ? h(value) : raw(value) %> <%= link_to("x", options[:remove], :class => "remove") %> </li>

app/views/catalog/_object_show_download.html.erb
<% if generic_file.audio? %>
    <% surrogate_type_name = "mp3" %>
<% elsif generic_file.video? %>
    <% surrogate_type_name = "webm" %>
<% elsif generic_file.pdf? %>
    <% surrogate_type_name = "pdf" %>
<% elsif generic_file.text? %>
    <% surrogate_type_name = "rtf" %>
<% elsif generic_file.image? %>
    <% surrogate_type_name = "full_size_web_format" %>
<% end %>

<% surrogate = surrogate_url(document.id, generic_file.id, surrogate_type_name) %>
<div class="carousel-caption">
  <p>
    <% if surrogate.nil? && !((@document.read_master? && can?(:read, @document.id)) || can?(:edit, @document.id)) %>
      <%= t('dri.views.catalog.links.download_not_available', :index => index.ordinalize) %>
    <% elsif surrogate.nil? && ((@document.read_master? && can?(:read, @document.id)) || can?(:edit, @document.id)) %>
        <%= link_to "#{t('dri.views.catalog.links.download_master')} (#{generic_file.file_size ? number_to_human_size(generic_file.file_size.to_f) : t('dri.views.catalog.links.unknown_size')})", file_download_path(@document, generic_file.id), :id => "download_master_asset" %>
    <% elsif surrogate.present? %>
        <%= link_to t('dri.views.catalog.links.download_nth', :index => index.ordinalize), surrogate_download_path(generic_file.id, :object_id => document.id, :surrogate_url => surrogate), :id => "download_asset" %>
        <% if (@document.read_master? && can?(:read, @document.id)) || can?(:edit, @document.id) %>
            - <%= link_to "#{t('dri.views.catalog.links.download_master')} (#{generic_file.file_size ? number_to_human_size(generic_file.file_size.to_f) : t('dri.views.catalog.links.unknown_size')})", file_download_path(@document, generic_file.id), :id => "download_master_asset" %>
        <% end %>
    <% end %>
  </p>
</div>

app/views/catalog/_paginate_compact.html.erb
<% if @response.total_pages > 1 %>
  <%= paginate @response, :outer_window => 1, :theme => :blacklight %>
<% end %>

app/views/catalog/_show_editor_tools.html.erb
<script>
  $(document).ready(function() {
    $('#dri_asset_uploader').change(function() {
      if ($(this).val()) {
        $('#dri_upload_asset_file').attr('style', 'display: inherit;');
      }
    });
    $('#dri_metadata_uploader').change(function() {
      if ($(this).val()) {
        $('#dri_upload_metadata_file').attr('style', 'display: inherit;');
      }
    });
    $('#dri_preservation_asset_uploader').change(function() {
      if ($(this).val()) {
        $('#dri_upload_preservation_asset_file').attr('style', 'display: inherit;');
      }
    });
  });
</script>
<div class="dri_sidenav">
<h5>
  <i class="fa fa-pencil"></i> <%= t('dri.views.catalog.titles.editor_tools') %>
</h5>
<ul>
  
  <li>
    <%= form_tag(url_for(object_files_path(@document.id)), :multipart => true, :method => :post, :id => "file_uploader") do %>
      <div class="dri_fileUpload">
       <%= t('dri.views.catalog.links.upload_file') %><%= button_tag t('dri.views.objects.buttons.upload'), :id => "dri_upload_asset_file", :name => "upload_file", :style => "display:none; margin-left: 5px;", :class => "dri_button_green_small" %>
        <%= file_field_tag 'Filedata', :required=>'required', :class => 'upload', :id => 'dri_asset_uploader' %>
      </div>
      <%= hidden_field_tag 'authenticity_token', form_authenticity_token %>
      <%= hidden_field_tag 'datastream', "content" %>
    <% end %>
  </li>

  <% if @files.present? %>
    <li>
      <%= form_tag(url_for(object_files_path(@document.id)), :multipart => true, :method => :post, :id => "file_uploader") do %>
        <%= hidden_field_tag "preservation", "true" %>
        <div class="dri_fileUpload">
        <%= t('dri.views.catalog.links.upload_preservation_file') %><%= button_tag t('dri.views.objects.buttons.upload'), :id => "dri_upload_preservation_asset_file", :name => "upload_file", :style => "display:none; margin-left: 5px;", :class => "dri_button_green_small"  %>
        <%= file_field_tag 'Presfiledata', :required=>'required', :class => 'upload', :id => 'dri_preservation_asset_uploader' %>
        </div>
        <%= hidden_field_tag 'authenticity_token', form_authenticity_token %>
        <%= hidden_field_tag 'datastream', "content" %>
     <% end %>
    </li>
 
    <%= link_to surrogates_generate_path(@document), :method => :put, data: { confirm: t('dri.views.objects.confirm.surrogates') }, :id => "surrogates_generate" do %>
      <li>
        <%= t('dri.views.catalog.links.generate_surrogates') %>
      </li>
    <% end %>
  <% end %>

  <% unless @document.published? %>
    <li>
      <%= form_tag status_update_path(@document.id) ,:method => :put do %>
        <% if @document.draft? %>
          <%= hidden_field_tag( :status, "reviewed") %>
          <span class="label label-danger"><%= t('dri.views.catalog.links.draft') %></span><%= submit_tag t('dri.views.catalog.links.mark_object_reviewed'), :id => 'status_update', :class => "pull-right dri_button_green_small" %>
        <% else %>
          <%= hidden_field_tag( :status, "draft") %>
          <span class="label label-success"><%= t('dri.views.catalog.links.reviewed') %></span><%= submit_tag t('dri.views.catalog.links.mark_object_draft'), :id => 'status_update', :class => "pull-right dri_button_red_small" %>
        <% end %>
      <% end %>
    </li>  

    <% if @document.editable? %>
      <%= link_to '', :'data-target' => '#dri_delete_object_modal_id', :'data-toggle' => 'modal' do %>
        <li>
          <%= t('dri.views.objects.buttons.delete_object') %>
        </li>
      <% end %>
    <% end %>
  <% end %>
  
  <li>
  <div class="accordion" id="dri_edit_record_tools_id">
    <div class="accordion-group">
      <a class="accordion-toggle" id="edit_menu" data-toggle="collapse" data-parent="#dri_edit_record_tools_id" href="#dri_edit_record_tools_collapsed_id">
        <i class="fa fa-caret-square-o-down fa-lg"></i> <%= t('dri.views.catalog.links.edit_this_record') %>
      </a>
     
      <div id="dri_edit_record_tools_collapsed_id" class="accordion-body collapse" style="height: 0px; ">
        <div class="accordion-inner">
          <ul class="dri_subnav_edit_list">              
           <% if @document.editable? %> 
            <%= link_to edit_object_path(@document), :id => "edit_record" do %>
              <li>
                <%= t('dri.views.catalog.buttons.edit_metadata') %>
              </li>
            <% end %>
            
            <!-- Replace metadata only visible if non-EAD collection AND not a Documentation object -->
            <% if @document.active_fedora_model != "DRI::Documentation" %>
              <li>
                <%= form_tag(url_for(:action=>"update", :controller=>"metadata", :id=>@document.id), :multipart => true, :method => :put, :id => "metadata_uploader") do %>
                  <div class="dri_fileUpload">
                    <%= t('dri.views.objects.legends.replace_metadata') %><%= button_tag t('dri.views.objects.buttons.upload'), :id => "dri_upload_metadata_file", :name => "upload_file", :style => "display:none; margin-left: 5px;", :class => "dri_button_green_small" %>
                    <%= file_field_tag 'metadata_file', :accept => "application/xml", :required => "true", :class => 'upload', :id => 'dri_metadata_uploader' %>
                  </div>
                  <%= hidden_field_tag 'authenticity_token', form_authenticity_token %>
                  <%= hidden_field_tag 'datastream', "content" %>
                <% end %>
              </li>
            <% end %> <!-- END IF (non-EAD collections AND not Documentation Object) -->
           <% end %>

            <li>
             <%= link_to t('dri.views.catalog.buttons.edit_access_controls'), access_controls_path(@document.id, format: 'js'), :id => "edit_access_controls", :remote => true, :'data-toggle' => 'modal',  :'data-target' => '#dri_access_controls_modal_id' %>
            </li>

            <%= link_to '', :'data-target' => '#dri_licence_modal_id', :'data-toggle' => 'modal', :id => "manage_licence" do %>
              <li class="dri_subnav_edit_list_last">
                <%= t('dri.views.catalog.buttons.set_licence') %>
               </li>
            <% end %>
          </ul>
      </div>
    </div>
  </div>
  </div>
  </li>
</ul>
</div>

<% if (can? :edit, @document) && @document.editable? && !@document.published? %>
<div class="modal fade" id="dri_delete_object_modal_id">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
          &times;
        </button>
        <h4 class="modal-title"><%= t('dri.views.objects.buttons.delete_object') %></h4>
      </div>

      <div class="modal-body">
        <span class="label label-danger"><%= t('dri.views.objects.confirm.delete') %></span>
        <br />
        <%= form_tag (object_path(@document.id)), :class=>'dri_ingest_form', :method => :delete, :style=>"margin:0;padding:0;display:inline;" do %>
          <%= submit_tag t('dri.views.objects.buttons.delete_object'), :class => "dri_button_red", :id => "delete_object_#{@document.id}", :data => { :confirm => t('dri.views.objects.confirm.delete') } %>
        <% end %>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">
          <%= t('dri.window.modal.close') %>
        </button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<% end %>

<div class="modal fade" id="dri_licence_modal_id">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
          &times;
        </button>
        <h4 class="modal-title"><%= t('dri.views.catalog.forms.manage_licence') %></h4>
      </div>

      <div class="modal-body">
        <%= render :partial => "shared/set_object_licence" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">
          <%= t('dri.window.modal.close') %>
        </button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" id="dri_access_controls_modal_id">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
          &times;
        </button>
        <h4 class="modal-title"><%= t('dri.views.catalog.forms.access_controls') %></h4>
      </div>

      <div class="modal-body"></div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">
          <%= t('dri.window.modal.close') %>
        </button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->